image: alpine/doctl:1.27.13 # comes with doctl, kubectl, and helm

# enable Docker for your repository
options:
  docker: true

pipelines:
  branches:
    main:
      - step:
          name: Put docker image into DO registry
          script:
            - doctl registry login --expiry-seconds 3600
            - export IMAGE_NAME=$IMAGE_TAG_NAME:$FLUTTER_VERSION
            - docker build -t $IMAGE_NAME $BITBUCKET_CLONE_DIR
            - docker push $IMAGE_NAME
          services:
            - docker
